### ISSUE TITLE
Updated chilitags.js

### ISSUE THREAD

**Issue by Victordmdb** [chili-epfl/chilitags#90]
If I try to use the chilitags-javascript.js file (available [here](https://github.com/chili-epfl/chilitags/tree/master/platforms/javascript)), I get "Module is not defined".

I've tried rebuilding it with the instructions there and emscripten, but that hasn't worked so far.

Does anyone have an update js file?

Cheers

**Comment by qbonnard** [comment]
This one is more up to date : http://quentin.bonnard.eu/portfolio/chilitags/demo/chilitags.js
Let me know if it helps, I'll update the repo with it in this case.

**Comment by Victordmdb** [comment]
That's amazing, thanks for the quick response!
